version: '3.6'

services:
  otusdb:
    image: mysql:8.0.18
    environment:
      - MYSQL_ROOT_PASSWORD=12345
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - ./custom.conf:/etc/mysql/conf.d
      - data:/var/lib/mysql
    expose:
      - "3306"
    ports:
      - "3309:3306"

volumes:
  data:
